In [10]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
#2. Data collection
online_retail_dataset = pd.read_excel("Online Retail.xlsx")
online_retail_dataset

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [2]:
#Due to large dataset converting dataset into smaller by contries that I am going to work
UK_retail_data = pd.read_csv('UK_retail_data.csv')
UK_retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,United Kingdom
...,...,...,...,...,...,...,...
361873,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,United Kingdom
361874,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,United Kingdom
361875,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,United Kingdom
361876,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,United Kingdom
361877,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,United Kingdom

In [3]:
#3. Data understanding
print(online_retail_dataset.shape)
print("================================")
print(online_retail_dataset.dtypes)
print("================================")
print(online_retail_dataset.isna().sum())
print("================================")
online_retail_dataset.describe(include="all")

(541909, 8)
================================
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object
================================
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

In [4]:
print("Missing description %",1454/541909)
print("Missing CustomerID %",135080/541909)

Missing description % 0.002683107311375157
Missing CustomerID % 0.249266943342886

In [5]:
#3. Data preprocessing
online_retail_dataset.dropna(inplace=True)

In [6]:
online_retail_dataset.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [7]:
online_retail_dataset.drop(labels="CustomerID",inplace=True,axis=1)

In [8]:
#countries list
online_retail_dataset["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Greece', 'Singapore', 'Lebanon',
       'United Arab Emirates', 'Saudi Arabia', 'Czech Republic', 'Canada',
       'Unspecified', 'Brazil', 'USA', 'European Community', 'Bahrain',
       'Malta', 'RSA'], dtype=object)

In [9]:
#country names and count
online_retail_dataset.value_counts("Country")

Country
United Kingdom          361878
Germany                   9495
France                    8491
EIRE                      7485
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               1877
Portugal                  1480
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
USA                        291
Israel                     250
Unspecified                244
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     17
Saudi Arabia                10
Name: count, dtype: int64

In [26]:
#UK retail data
# UK_retail_data = online_retail_dataset[online_retail_dataset["Country"]=="United Kingdom"]
# UK_retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,United Kingdom
...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,United Kingdom

In [27]:
#UK_retail_data.to_csv("UK_retail_data.csv",index=False)

In [4]:
pivotted_UK_data = pd.pivot_table(data=UK_retail_data,values="Quantity",index="InvoiceNo",columns="Description",aggfunc = "sum")

In [30]:
#Bahrain retail data
Bahrain_retail_data = online_retail_dataset[online_retail_dataset["Country"]=="Bahrain"]
Bahrain_retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
181140,552449,22693,GROW A FLYTRAP OR SUNFLOWER IN TIN,24,2011-05-09 13:49:00,1.25,Bahrain
181141,552449,23076,ICE CREAM SUNDAE LIP GLOSS,96,2011-05-09 13:49:00,1.25,Bahrain
181142,552449,23077,DOUGHNUT LIP GLOSS,60,2011-05-09 13:49:00,1.25,Bahrain
181143,552449,22890,NOVELTY BISCUITS CAKE STAND 3 TIER,2,2011-05-09 13:49:00,9.95,Bahrain
181144,552449,22649,STRAWBERRY FAIRY CAKE TEAPOT,8,2011-05-09 13:49:00,4.95,Bahrain
181145,552449,22423,REGENCY CAKESTAND 3 TIER,2,2011-05-09 13:49:00,12.75,Bahrain
181146,552449,85040A,S/4 PINK FLOWER CANDLES IN BOWL,12,2011-05-09 13:49:00,1.65,Bahrain
181147,552449,22699,ROSES REGENCY TEACUP AND SAUCER,6,2011-05-09 13:49:00,2.95,Bahrain
181148,552449,22697,GREEN REGENCY TEACUP AND SAUCER,6,2011-05-09 13:49:00,2.95,Bahrain
181149,552449,22698,PINK REGENCY TEACUP AND SAUCER,6,2011-05-09 13:49:00,2.95,Bahrain
181150,552449,72802A,ROSE SCENT CANDLE IN JEWELLED BOX,6,2011-05-09 13:49:00,4.25,Bahrain
181151,552449,72802B,OCEAN SCENT CANDLE IN JEWELLED BOX,6,2011-05-09 13:49:00,4.25,Bahrain
181152,552449,72802C,VANILLA SCENT CANDLE JEWELLED BOX,6,2011-05-09 13:49:00,4.25,Bahrain
197371,553900,37449,CERAMIC CAKE STAND + HANGING CAKES,2,2011-05-19 17:47:00,9.95,Bahrain
197372,553900,37446,MINI CAKE STAND WITH HANGING CAKES,8,2011-05-19 17:47:00,1.45,Bahrain
197373,553900,22890,NOVELTY BISCUITS CAKE STAND 3 TIER,4,2011-05-19 17:47:00,9.95,Bahrain
197374,553900,37450,CERAMIC CAKE BOWL + HANGING CAKES,6,2011-05-19 17:47:00,2.95,Bahrain

In [13]:
# pd.pivot(data=Bahrain_retail_data,columns="Description",
#     index = "InvoiceNo",
#     values = "Quantity",aggfunc = "sum")

In [14]:
pd.pivot_table(data=Bahrain_retail_data,columns="Description",
    index = "InvoiceNo",
    values = "Quantity",aggfunc = "sum")
#pivot table can handle if the index and description has duplicate values it can sum the quantities but pivot can also work becuase there is not duplicate entries for description

Description,CERAMIC CAKE BOWL + HANGING CAKES,CERAMIC CAKE STAND + HANGING CAKES,DOUGHNUT LIP GLOSS,GREEN REGENCY TEACUP AND SAUCER,GROW A FLYTRAP OR SUNFLOWER IN TIN,ICE CREAM SUNDAE LIP GLOSS,MINI CAKE STAND WITH HANGING CAKES,NOVELTY BISCUITS CAKE STAND 3 TIER,OCEAN SCENT CANDLE IN JEWELLED BOX,PINK REGENCY TEACUP AND SAUCER,REGENCY CAKESTAND 3 TIER,ROSE SCENT CANDLE IN JEWELLED BOX,ROSES REGENCY TEACUP AND SAUCER,S/4 PINK FLOWER CANDLES IN BOWL,STRAWBERRY FAIRY CAKE TEAPOT,VANILLA SCENT CANDLE JEWELLED BOX
InvoiceNo,,,,,,,,,,,,,,,,
552449,NaN,NaN,60.0,6.0,24.0,96.0,NaN,2.0,6.0,6.0,2.0,6.0,6.0,12.0,8.0,6.0
553900,6.0,2.0,NaN,NaN,NaN,NaN,8.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pivotted_UK_data.fillna(0,inplace = True)
one_hot_encoded_pivotted_UK_data = pivotted_UK_data.applymap(func = lambda x: 0 if x == 0 else 1)

In [7]:
# 4. Data Mining
from mlxtend.frequent_patterns import apriori,association_rules

In [12]:
apriori(df = one_hot_encoded_pivotted_UK_data,min_support=0.02)

      support      itemsets
0    0.031727         (101)
1    0.021756         (105)
2    0.029864         (107)
3    0.022561         (111)
4    0.035655         (141)
..        ...           ...
163  0.020799  (1937, 1939)
164  0.021000  (1937, 1941)
165  0.022108  (2307, 2302)
166  0.021806  (3681, 2684)
167  0.023317  (3745, 3741)

[168 rows x 2 columns]

In [11]:
frequent_item_sets=apriori(df = one_hot_encoded_pivotted_UK_data,min_support=0.02,use_colnames=True)
frequent_item_sets

      support                                           itemsets
0    0.031727                           (6 RIBBONS RUSTIC CHARM)
1    0.021756                  (60 CAKE CASES VINTAGE CHRISTMAS)
2    0.029864                      (60 TEATIME FAIRY CAKE CASES)
3    0.022561                   (72 SWEETHEART FAIRY CAKE CASES)
4    0.035655                       (ALARM CLOCK BAKELIKE GREEN)
..        ...                                                ...
163  0.020799  (LUNCH BAG SPACEBOY DESIGN , LUNCH BAG RED RET...
164  0.021000  (LUNCH BAG SUKI DESIGN , LUNCH BAG RED RETROSPOT)
165  0.022108  (PAPER CHAIN KIT VINTAGE CHRISTMAS, PAPER CHAI...
166  0.021806  (RED HANGING HEART T-LIGHT HOLDER, WHITE HANGI...
167  0.023317  (WOODEN FRAME ANTIQUE WHITE , WOODEN PICTURE F...

[168 rows x 2 columns]

In [15]:
best_associates = association_rules(df=frequent_item_sets,metric='confidence',min_threshold=0.02)
best_associates

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED ),0.035655,0.039633,0.023166,0.649718,16.393190,1.0,0.021753,2.741692,0.973717,0.444444,0.635262,0.617108
1,(ALARM CLOCK BAKELIKE RED ),(ALARM CLOCK BAKELIKE GREEN),0.039633,0.035655,0.023166,0.584498,16.393190,1.0,0.021753,2.320916,0.977751,0.444444,0.569136,0.617108
2,(GARDENERS KNEELING PAD CUP OF TEA ),(GARDENERS KNEELING PAD KEEP CALM ),0.031928,0.037871,0.023216,0.727129,19.200276,1.0,0.022007,3.525953,0.979181,0.498378,0.716389,0.670081
3,(GARDENERS KNEELING PAD KEEP CALM ),(GARDENERS KNEELING PAD CUP OF TEA ),0.037871,0.031928,0.023216,0.613032,19.200276,1.0,0.022007,2.501684,0.985229,0.498378,0.600269,0.670081
4,(PINK REGENCY TEACUP AND SAUCER),(GREEN REGENCY TEACUP AND SAUCER),0.026389,0.032633,0.020748,0.786260,24.093759,1.0,0.019887,4.525894,0.984474,0.542105,0.779049,0.711031
5,(GREEN REGENCY TEACUP AND SAUCER),(PINK REGENCY TEACUP AND SAUCER),0.032633,0.026389,0.020748,0.635802,24.093759,1.0,0.019887,2.673306,0.990830,0.542105,0.625931,0.711031
6,(ROSES REGENCY TEACUP AND SAUCER ),(GREEN REGENCY TEACUP AND SAUCER),0.036461,0.032633,0.024576,0.674033,20.654747,1.0,0.023386,2.967684,0.987593,0.552036,0.663037,0.713560
7,(GREEN REGENCY TEACUP AND SAUCER),(ROSES REGENCY TEACUP AND SAUCER ),0.032633,0.036461,0.024576,0.753086,20.654747,1.0,0.023386,3.902334,0.983686,0.552036,0.743743,0.713560
8,(HEART OF WICKER LARGE),(HEART OF WICKER SMALL),0.040641,0.047288,0.020094,0.494424,10.455563,1.0,0.018172,1.884408,0.942668,0.296214,0.469329,0.459672
9,(HEART OF WICKER SMALL),(HEART OF WICKER LARGE),0.047288,0.040641,0.020094,0.424920,10.455563,1.0,0.018172,1.668219,0.949245,0.296214,0.400558,0.459672
10,(JUMBO BAG RED RETROSPOT),(JUMBO BAG PINK POLKADOT),0.074885,0.041547,0.025885,0.345662,8.319780,1.0,0.022774,1.464768,0.951022,0.285873,0.317298,0.484346
11,(JUMBO BAG PINK POLKADOT),(JUMBO BAG RED RETROSPOT),0.041547,0.074885,0.025885,0.623030,8.319780,1.0,0.022774,2.454082,0.917942,0.285873,0.592516,0.484346
12,(JUMBO BAG STRAWBERRY),(JUMBO BAG RED RETROSPOT),0.031979,0.074885,0.020295,0.634646,8.474888,1.0,0.017900,2.532102,0.911141,0.234439,0.605071,0.452831
13,(JUMBO BAG RED RETROSPOT),(JUMBO BAG STRAWBERRY),0.074885,0.031979,0.020295,0.271015,8.474888,1.0,0.017900,1.327904,0.953400,0.234439,0.246933,0.452831
14,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SUKI),0.074885,0.037115,0.021000,0.280430,7.555640,1.0,0.018221,1.338140,0.937882,0.230769,0.252694,0.423119
15,(JUMBO STORAGE BAG SUKI),(JUMBO BAG RED RETROSPOT),0.037115,0.074885,0.021000,0.565807,7.555640,1.0,0.018221,2.130654,0.901093,0.230769,0.530661,0.423119
16,(LUNCH BAG BLACK SKULL.),(LUNCH BAG CARS BLUE),0.051166,0.045576,0.020446,0.399606,8.767936,1.0,0.018114,1.589664,0.933723,0.267987,0.370936,0.424113
17,(LUNCH BAG CARS BLUE),(LUNCH BAG BLACK SKULL.),0.045576,0.051166,0.020446,0.448619,8.767936,1.0,0.018114,1.720832,0.928254,0.267987,0.418886,0.424113
18,(LUNCH BAG BLACK SKULL.),(LUNCH BAG PINK POLKADOT),0.051166,0.043713,0.022410,0.437992,10.019827,1.0,0.020174,1.701555,0.948741,0.309243,0.412302,0.475332
19,(LUNCH BAG PINK POLKADOT),(LUNCH BAG BLACK SKULL.),0.043713,0.051166,0.022410,0.512673,10.019827,1.0,0.020174,1.947017,0.941347,0.309243,0.486394,0.475332
20,(LUNCH BAG BLACK SKULL.),(LUNCH BAG RED RETROSPOT),0.051166,0.058267,0.024676,0.482283,8.277185,1.0,0.021695,1.819014,0.926596,0.291147,0.450251,0.452896
21,(LUNCH BAG RED RETROSPOT),(LUNCH BAG BLACK SKULL.),0.058267,0.051166,0.024676,0.423509,8.277185,1.0,0.021695,1.645879,0.933583,0.291147,0.392422,0.452896
22,(LUNCH BAG PINK POLKADOT),(LUNCH BAG CARS BLUE),0.043713,0.045576,0.020194,0.461982,10.136539,1.0,0.018202,1.773962,0.942548,0.292274,0.436290,0.452538
23,(LUNCH BAG CARS BLUE),(LUNCH BAG PINK POLKADOT),0.045576,0.043713,0.020194,0.443094,10.136539,1.0,0.018202,1.717143,0.944388,0.292274,0.417637,0.452538
24,(LUNCH BAG RED RETROSPOT),(LUNCH BAG CARS BLUE),0.058267,0.045576,0.021151,0.363008,7.964912,1.0,0.018496,1.498329,0.928553,0.255786,0.332590,0.413548
25,(LUNCH BAG CARS BLUE),(LUNCH BAG RED RETROSPOT),0.045576,0.058267,0.021151,0.464088,7.964912,1.0,0.018496,1.757255,0.916206,0.255786,0.430931,0.413548
26,(LUNCH BAG RED RETROSPOT),(LUNCH BAG PINK POLKADOT),0.058267,0.043713,0.024072,0.413137,9.451233,1.0,0.021525,1.629491,0.949519,0.308985,0.386312,0.481914
27,(LUNCH BAG PINK POLKADOT),(LUNCH BAG RED RETROSPOT),0.043713,0.058267,0.024072,0.550691,9.451233,1.0,0.021525,2.095960,0.935068,0.308985,0.522892,0.481914
28,(LUNCH BAG SPACEBOY DESIGN ),(LUNCH BAG RED RETROSPOT),0.044569,0.058267,0.020799,0.466667,8.009162,1.0,0.018202,1.765750,0.915966,0.253530,0.433668,0.411812
29,(LUNCH BAG RED RETROSPOT),(LUNCH BAG SPACEBOY DESIGN ),0.058267,0.044569,0.020799,0.356958,8.009162,1.0,0.018202,1.485798,0.929290,0.253530,0.326961,0.411812
30,(LUNCH BAG SUKI DESIGN ),(LUNCH BAG RED RETROSPOT),0.042907,0.058267,0.021000,0.489437,8.399951,1.0,0.018500,1.844499,0.920445,0.261935,0.457847,0.424926
31,(LUNCH BAG RED RETROSPOT),(LUNCH BAG SUKI DESIGN ),0.058267,0.042907,0.021000,0.360415,8.399951,1.0,0.018500,1.496428,0.935458,0.261935,0.331742,0.424926
32,(PAPER CHAIN KIT VINTAGE CHRISTMAS),(PAPER CHAIN KIT 50'S CHRISTMAS ),0.034648,0.048044,0.022108,0.638081,13.281323,1.0,0.020443,2.630305,0.957895,0.364921,0.619816,0.549125
33,(PAPER CHAIN KIT 50'S CHRISTMAS ),(PAPER CHAIN KIT VINTAGE CHRISTMAS),0.048044,0.034648,0.022108,0.460168,13.281323,1.0,0.020443,1.788245,0.971375,0.364921,0.440792,0.549125
34,(RED HANGING HEART T-LIGHT HOLDER),(WHITE HANGING HEART T-LIGHT HOLDER),0.032986,0.096893,0.021806,0.661069,6.822683,1.0,0.018610,2.664573,0.882541,0.201771,0.624705,0.443060
35,(WHITE HANGING HEART T-LIGHT HOLDER),(RED HANGING HEART T-LIGHT HOLDER),0.096893,0.032986,0.021806,0.225052,6.822683,1.0,0.018610,1.247844,0.944993,0.201771,0.198618,0.443060
36,(WOODEN FRAME ANTIQUE WHITE ),(WOODEN PICTURE FRAME WHITE FINISH),0.040137,0.043813,0.023317,0.580928,13.259192,1.0,0.021558,2.281679,0.963242,0.384551,0.561726,0.556556
37,(WOODEN PICTURE FRAME WHITE FINISH),(WOODEN FRAME ANTIQUE WHITE ),0.043813,0.040137,0.023317,0.532184,13.259192,1.0,0.021558,2.051796,0.966946,0.384551,0.512622,0.556556

In [ ]:
best