In [1]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
     ---------- ----------------------------- 0.4/1.4 MB 7.6 MB/s eta 0:00:01
     ----------------------- ---------------- 0.8/1.4 MB 10.1 MB/s eta 0:00:01
     ------------------------------------ --- 1.2/1.4 MB 9.7 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 7.1 MB/s eta 0:00:00
  Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
     ------------ --------------------------- 0.4/1.4 MB 13.5 MB/s eta 0:00:01
     ------------------- -------------------- 0.7/1.4 MB 7.1 MB/s eta 0:00:01
     ---------------------------------- ----- 1.2/1.4 MB 8.1 MB/s eta 0:00:01
     ---------------------------------------  1.4/1.4 MB 7.1 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 6.1 MB/s eta 0:00:00
Requirement already satisfied: joblib>=0.13.2 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scipy>=1.2.1 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (3.10.8)
Requirement already satisfied: numpy>=1.16.2 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (2.2.6)
Requirement already satisfied: pandas>=0.24.2 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from mlxtend) (1.7.2)
Requirement already satisfied: pyparsing>=3 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.61.1)
Requirement already satisfied: pillow>=8 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (12.1.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\aswath\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
     ---- ----------------------------------- 30.7/250.9 kB ? eta -:--:--
     -------------- ------------------------ 92.2/250.9 kB 1.3 MB/s eta 0:00:01
     --------------------- ---------------- 143.4/250.9 kB 1.1 MB/s eta 0:00:01
     ------------------------ ----------- 174.1/250.9 kB 958.1 kB/s eta 0:00:01
     -------------------------------------- 250.9/250.9 kB 1.1 MB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [6]:
#2. Data collection
online_retail_dataset = pd.read_excel("Online Retail.xlsx")
online_retail_dataset

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [14]:
#3. Data understanding
print(online_retail_dataset.shape)
print("================================")
print(online_retail_dataset.dtypes)
print("================================")
print(online_retail_dataset.isna().sum())
print("================================")
online_retail_dataset.describe(include="all")

(406829, 7)
================================
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
Country                object
dtype: object
================================
InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64
================================

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
count,406829.0,406829,406829,406829.000000,406829,406829.000000,406829
unique,22190.0,3684,3896,NaN,NaN,NaN,37
top,576339.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,United Kingdom
freq,542.0,2077,2070,NaN,NaN,NaN,361878
mean,NaN,NaN,NaN,12.061303,2011-07-10 16:30:57.879207424,3.460471,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,0.000000,NaN
25%,NaN,NaN,NaN,2.000000,2011-04-06 15:02:00,1.250000,NaN
50%,NaN,NaN,NaN,5.000000,2011-07-31 11:48:00,1.950000,NaN
75%,NaN,NaN,NaN,12.000000,2011-10-20 13:06:00,3.750000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,NaN
std,NaN,NaN,NaN,248.693370,NaN,69.315162,NaN

In [8]:
print("Missing description %",1454/541909)
print("Missing CustomerID %",135080/541909)

Missing description % 0.002683107311375157
Missing CustomerID % 0.249266943342886

In [9]:
#3. Data preprocessing
online_retail_dataset.dropna(inplace=True)

In [10]:
online_retail_dataset.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [12]:
online_retail_dataset.drop(labels="CustomerID",inplace=True,axis=1)

In [20]:
#countries list
online_retail_dataset["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Greece', 'Singapore', 'Lebanon',
       'United Arab Emirates', 'Saudi Arabia', 'Czech Republic', 'Canada',
       'Unspecified', 'Brazil', 'USA', 'European Community', 'Bahrain',
       'Malta', 'RSA'], dtype=object)

In [17]:
#country names and count
online_retail_dataset.value_counts("Country")

Country
United Kingdom          361878
Germany                   9495
France                    8491
EIRE                      7485
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               1877
Portugal                  1480
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
USA                        291
Israel                     250
Unspecified                244
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     17
Saudi Arabia                10
Name: count, dtype: int64

In [23]:
#UK retail data
UK_retail_data = online_retail_dataset[online_retail_dataset["Country"]=="United Kingdom"]
UK_retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,United Kingdom
...,...,...,...,...,...,...,...
541889,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,2011-12-09 12:31:00,1.95,United Kingdom
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,United Kingdom
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,United Kingdom
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,United Kingdom
541893,581586,20685,DOORMAT RED RETROSPOT,10,2011-12-09 12:49:00,7.08,United Kingdom

In [26]:
pd.pivot_table(data=UK_retail_data,values="Quantity",index="InvoiceNo",columns="Description")

Description,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,DOLLY GIRL BEAKER,I LOVE LONDON MINI BACKPACK,NINE DRAWER OFFICE TIDY,OVAL WALL MIRROR DIAMANTE,RED SPOT GIFT BAG LARGE,SET 2 TEA TOWELS I LOVE LONDON,SPACEBOY BABY GIFT SET,TOADSTOOL BEDSIDE LIGHT,...,ZINC STAR T-LIGHT HOLDER,ZINC SWEETHEART SOAP DISH,ZINC SWEETHEART WIRE LETTER RACK,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,ZINC WIRE KITCHEN ORGANISER,ZINC WIRE SWEETHEART LETTER TRAY
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
536369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C581484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C581490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-11.0,NaN,NaN,NaN,NaN
C581499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C581568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C581569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# 4. Data Mining
from mlxtend.frequent_patterns import apriori,association_rules

In [ ]:
association_rules(df=,metric='confidence',min_threshold=0.8)